SET SCHEMA APP;
CREATE TABLE NOM_EQ_STATUSES(
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	DESCRIPTION VARCHAR(256) NOT NULL
);

CREATE TABLE NOM_EQ_TYPES(
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	DESCRIPTION VARCHAR(256) NOT NULL
);

CREATE TABLE NOM_ME_TYPES(
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	DESCRIPTION VARCHAR(256) NOT NULL
);

CREATE TABLE MAIN_HALLS(
	HALL_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	HALL_NAME VARCHAR(50) NOT NULL,
	HALL_FLOOR INTEGER NOT NULL,
	HALL_CAPACITY INTEGER NOT NULL
);

CREATE TABLE MAIN_EQUIPMENT_INVENTORY(
	EQ_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	EQ_TYPE_ID INTEGER NOT NULL,	
	EQ_COUNT_AVAILABLE INTEGER NOT NULL
);

CREATE TABLE MAIN_REQUESTS_EQUIPMENT(    	
	REQ_ID INTEGER NOT NULL,	
	REQ_EQ_TYPE_ID INTEGER NOT NULL,	
	REQ_EQ_COUNT INTEGER NOT NULL,
	REQ_EQ_POSITIONS VARCHAR(4096)    
);

CREATE TABLE MAIN_REQUESTS(    	
	REQ_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),	
	REQ_NAME VARCHAR(200),
    REQ_CU_ID VARCHAR(15) NOT NULL,
    REQ_START_DATE TIMESTAMP NOT NULL,
    REQ_END_DATE TIMESTAMP NOT NULL
);

CREATE TABLE MAIN_MEETINGS(
	ME_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	ME_NAME VARCHAR(50) NOT NULL,
	ME_TYPE_ID INTEGER NOT NULL,	
	ME_DESC VARCHAR(256) NOT NULL,
	ME_REQ_ID INTEGER
);

CREATE TABLE MAIN_SCHEDULE(
	SCH_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	SCH_HALL_ID INTEGER NOT NULL,
	SCH_ME_ID INTEGER NOT NULL,
	ME_START_DATE TIMESTAMP NOT NULL,
	ME_END_DATE TIMESTAMP NOT NULL	
);


CREATE TABLE USERS (
  user_name         varchar(15) not null primary key,
  user_pass         varchar(15) not null,
  user_mail         varchar(40) not null,
  user_realName     varchar(40)
);

CREATE TABLE USER_ROLES (
  user_name         varchar(15) not null,
  role_name         varchar(15) not null,
  primary key (user_name, role_name)
);
